name: CI and Deploy

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run cargo test
      run: cargo test --all --locked

    - name: Run cargo clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  deploy:
    needs: test-and-lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: YOUR_AWS_REGION

    - name: Deploy Lambda
      run: |
        # Ensure you have a deployment script or CLI command
        ./deploy-lambda.sh  # Replace this with your actual deploy script or commands
