name: Deploy Rust Lambda

on:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cache Rust dependencies for faster builds
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-build-cache

      - name: Install cargo-lambda
        run: cargo install cargo-lambda

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Configure AWS Credentials for Deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::728092359661:role/github-actions-role
          aws-region: eu-west-2

      - name: Run cargo test
        run: cargo test --workspace --locked

      - name: Build Rust Lambda
        run: |
          cargo lambda build \
            --release --arm64 \
            --output-format zip

      - name: Deploy lambda
        run: cargo lambda deploy

permissions:
  id-token: write
  contents: read